<footer>
	<div class="column grid_4">
		<ul>
			<li><a href="about.html">About me</a></li>
			<li><a href="http://bogusart.wordpress.com/"><img src="img/icons/wordpress-icon-24.png"></a></li>
			<li><a href="http://www.facebook.com/z.boguslawski"><img src="img/icons/facebook-icon-24.png"></a></li>
			<li><a href="http://www.myspace.com/bogusart"><img src="img/icons/myspace-icon-24.png"></a></li>
		</ul>
	</div>
</footer>